# Generated by Django 5.0.7 on 2024-10-31 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Date', models.DateField()),
                ('start_time', models.TimeField()),
                ('Duration', models.DurationField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meeting', to='meetings.rooms')),
            ],
        ),
    ]
