# Generated by Django 5.0.7 on 2024-11-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_rooms_capacity_rooms_has_projector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='Duration',
            field=models.DurationField(help_text='Duration of booking in Hrs'),
        ),
    ]
